version: '3.3'

networks:
  todolist-network:
    driver: bridge

services:
  dbMysql:
    image: mysql:8.0
    container_name: gestao-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gestao_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    networks:
      - todolist-network
    volumes:
      - gestao-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: gestao-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    networks:
      - todolist-network
    ports:
      - 8081:80
    depends_on:
      - dbMysql

  php:
    image: bitnami/laravel:9
    container_name: gestao-app
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - './todolist:/app'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=dbMysql
      - DB_PORT=3306
      - DB_DATABASE=gestao_db
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
    networks:
      - todolist-network
    depends_on:
      - dbMysql

volumes:
  gestao-db-data:
